version: '3.11'
services:
  app:
    container_name: Greenhouse2-Main
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: python app.py


  db:
    container_name: Greenhouse2-db
    image: postgres:16.0-alpine
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  grafana:
    container_name: Greenhouse2-grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    container_name: Greenhouse2-nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - grafana